config:
    items:
      #example item
        EspadaJebus: 
            enchantments: 
                 sharpness: "10"
                 bane_of_arthropods: "10"
            custommodeldata: "340" #(custom model data for your resource pack) if you put leters, dev will be angry.
            name: "&4&lEspada de jebus"   #name here to show in game
            lore: 
                - "&b&cEspada forjada en jebuslandia" #lore of item
                - "&4&lCon el sabor a salute"
            #damageadition: "3" #(number for damage adition only weapons)
              #armoradition: "10" (number for armoradition only armors)
            itemtype: "weapon" #(can be armor, weapon or tools this is for gui)
            itemid: "DIAMOND_SWORD" 
            requirements:
                titanio: "10" #name of mineral to craft and quantity
            gui:
                page: "1"
                slot: "1"
            #funnyenchantments (will be add in next version)"
        
          
    minerals:
        titanio:  
            itemid: "DIAMOND_ORE" 
            name: "&4&ltitanio" #Name show in game 
            lore: 
                - "&C&LUn titanio forjado desde francia" #lore for mineral
                - "chuletina chuletona"
            custommodeldata: "19203" #(custom model data for your resource pack)

    menugui:
        inventoryname: "&4CustomItems Menu"
        tool:
            lore:
                - "Herramientas exlusivas"
                - "Se compran con minerales exclusivos"
            displayname: "Comprar herramientas exlusivas"
            
        armor:
            lore:
                - "Armaduras exlusivas"
                - "Se compran con minerales exclusivos"
            displayname: "Comprar armaduras exlusivas"
            
        weapon:
            lore:
                - "Armas exlusivas"
                - "Se compran con minerales exclusivos"
            displayname: "Comprar armas exlusivas"
        
        elytra:
            lore:
                - "Elytras exlusivas"
                - "Se compran con minerales exlusivos"
            displayname: "Comprar elytras exlusivas"
            
            
    armorgui:
        name: "&4&LCustom armor"
        nextpageitem: "REDSTONE"
        nextpagename: "Siguiente Pagina"
        nextpagelore:
            - "Pasar a la siguiente pagina"    
        previouspageitem: "REDSTONE"
        previouspagename: "Pagina anterior"    
        previouspagelore: 
            - "Pasar a la pagina anterior"
        
        cost-of-item: "El item cuesta %mineral% x%quantity%"

    messages:
        insufficient-ore: "No tienes ores suficientes"
        reload-config: "&4&L La configuracion fue reiniciada"
        insuficient-resources: "No tienes recursos suficientes para recibir este item"
        insuficient-permissions: "&4&LNo tienes permisos suficientes para ejecutar este comando"
        item-not-exists: "El item no existe"
        mineral-not-exists: "El mineral %mineral% no existe"
        no-disponible-slot: "No hay espacio suficiente para realizar esta accion"
        received-item: "Recibiste correctamente el item %item%"
        received-mineral: "Recibiste correctamente el mineral %mineral%"
        item-not-exist: "&4&lEl item %item% no existe en tu lista de items"
        command-item-ussage: "El comando correcto para realizar esta accion es /givecustomitem <nameid> <quantity> {player}"
        command-mineral-ussage: "El comando correcto para realizar esta accion es /givecustommineral <nameid> <quantity> {player}"
        target-not-exists: "El jugador %player% al que le quieres dar el item no existe"
        unexpected-error: "Error inesperado, por favor comunicate con el developer"
          