name: customitems
main: customitems.main.Main
version: 1.0
author: ICUERVOI
api-version: 1.16
commands:
  givecustomitem:
    usage: /<command>
  givecustommineral:
    usage: /<command>
  buycustomitem:
    usage: /<command>
  customitemreload:
    usage: /<command>